name: Criar report de alterações realizadas
on:
  pull_request_target: 
    types: [opened, edited, closed, reopened]
  
jobs:
  baixar-repo:
    runs-on: ubuntu-latest
    name: PR Check Dependencies
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        token: ${{secrets.VACUUM_TOKEN}}
    
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    #Quando executar, trocar o caminho do arquivo para o arquivo que está sendo enviado
    - name: executar o vacuum com GO
      run: 'go run github.com/daveshanley/vacuum@latest html-report swagger-apis/automatic-payments/2.0.0-rc.4.yml ~/html-report.html'

    - name: armazenar o html de saida
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: ~/html-report.html
    
    - name: Baixar o report
      uses: actions/download-artifact@v4
      with:
        name: html-report